# App name
spring.application.name=logsense
# Log file settings
logging.file.name=logs/logsense.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
# Log levels
logging.level.root=INFO
logging.level.com.nirmala.logsense=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Anomaly Detection Config
logsense.detection.windowSize=5
logsense.detection.minimumStandardDeviation=1.0
logsense.detection.minimumSamples=1
logsense.detection.threshold=2.0
#Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/log_monitoring
spring.datasource.username=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true